name: Deploy to nginx

on:
 push:
  branches:
   - master

jobs:
 deploy_apache:
  runs-on: ubuntu-latest

  steps:
   - name: Checkout code
     uses: actions/checkout@v2

   - name: Start SSH Agent and Add Key for Nginx
     run: |
      eval "$(ssh-agent -s)"
      echo "${SSH_PRIVATE_KEY_NGINX}" | ssh-add -
     env:
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      SSH_PRIVATE_KEY_NGINX: ${{ secrets.SSH_PRIVATE_KEY_NGINX }}


   - name: Configure SSH key for Nginx
     run: |
      mkdir -p ~/.ssh
      echo "$SSH_PRIVATE_KEY_NGINX" > ~/.ssh/id_rsa
      chmod 600 ~/.ssh/id_rsa
      ssh-keyscan -t rsa pikso.in >> ~/.ssh/known_hosts
     env:
      SSH_PRIVATE_KEY_NGINX: ${{ secrets.SSH_PRIVATE_KEY_NGINX }}

   - name: Set execute permissions for the Nginx deployment script
     run: chmod +x ./deploy_nginx.sh

   - name: Run Nginx deployment script
     run: |
      bash ./deploy_nginx.sh
     env:
      NODE_ENV: production
